spring.application.name=Quantum-Zone-Backend

spring.datasource.url=jdbc:mysql://quantumzone1.mysql.database.azure.com:3306/quantumzone?useSSL=true&requireSSL=true
spring.datasource.username=AdminQuantumZone1781
spring.datasource.password=6.Fc>F&O@j1X}131
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

JWT_SECRET=4UdO8lFXizWNFsU+YshbOFZ8ERvBL1nPCheun0c4zbuYsN4MbZbk3jRJIOzuQ/cmA5V4UjPFe8G4jKBZ/9hJyVMBleLrDL6LjGBVIZ/KqNB/++tKIlP4rgGGHfmCwUY/AuEXAVk39oKZfjOxSNXrYXTw+zgzE779dMtCOe+0VTCcJ1u8K191MXTlvzKFUvthVcMX5JgyJoKG0LiBM8gI3wC0zZQ5JccOE5C+2YxRB5rn23UXRkFpHv/RjhlCcljRDQskVaBYdnaFZTRgrqVUXNBkrJtXS1G9CIFzPzOgf32y8y4dgwTeTUxFTCkES9X7PmI8j//QJha1UTExNfrznA==